Amend the README to add more details about KMS key.
ministryofjustice/modernisation-platform-ami-builds pull request #22
Opened 2022-03-10 11:47 UTC by SteveLinden

Added  links to relevant pull requests with code change details.

2022-03-16 13:59 UTC, davidkelliott requested changes
Could the new information be put in it's own section please?  Something like:
"### How to use the per business unit shared kms key"

With a bit of information explaining that anyone in the business unit for that key can access and use it, and that images encrypted with the key will be accessible to all accounts in the business unit?  Thanks

2022-03-16 13:59 UTC, davidkelliott commented on README.md
> +More details of the required change can be seen in https://github.com/ministryofjustice/modernisation-platform-ami-builds/pull/18/files/6a589a6d3d0dc70f2bc28cb8cbb84075cad9d73c - ignore the rhel7 sec
I think there is too much information in this PR for it to be useful as an example here

2022-03-16 13:59 UTC, davidkelliott commented on README.md
> +Should you have a shared kms key the above would not be required. If a default key is to be used this is already in place in the template, as below\
There is a trailing \ at the end of a few lines

2022-03-16 13:59 UTC, davidkelliott commented on README.md
> +If, however, a customer key is needed then the following needs to be set up
This is covered in the section above "### How to add your own team kms key"

2022-03-16 13:59 UTC, davidkelliott commented on README.md
> +*__sprinkler example__*
This is covered already in the above section

2022-03-16 13:59 UTC, davidkelliott commented on README.md
> +'data "aws_kms_key" "ebs_encryption_cmk" {key_id = "arn:aws:kms:eu-west-2:${data.aws_caller_identity.current.account_id}:alias/ebs-encryption-key"}'\
This wouldn't give the per business unit key, you would need something like:

`data "aws_kms_key" "ebs_encryption_cmk" {key_id = "arn:aws:kms:eu-west-2:${data.aws_caller_identity.current.account_id}:alias/ebs-<business-unit>"}`

For example:

`data "aws_kms_key" "ebs_encryption_cmk" {key_id = "arn:aws:kms:eu-west-2:${data.aws_caller_identity.current.account_id}:alias/ebs-hmpps"}`

2022-03-28 13:19 UTC, davidkelliott requested changes
I've added in some suggestions to make the guide read a little clearer and sort some formatting out.  After these are accepted I can approve 👍

2022-03-28 13:46 UTC, davidkelliott requested changes
It would be good to include an example of how to create a team kms key before showing how to reference it.  Something like:

Example code on how to create a team KMS key, and the permissions needed can be found [here](https://github.com/ministryofjustice/modernisation-platform-environments/blob/b73bba2e9d708efbc0db4492582829f52f00cb60/terraform/environments/sprinkler/kms.tf).

2022-03-28 13:49 UTC, SteveLinden commented on README.md
> +
Complete

2022-03-28 13:49 UTC, SteveLinden commented on README.md
> +If, however, a customer key is needed then follow the instructions in the section "### How to add your own team kms key".
Completed

2022-03-28 14:03 UTC, davidkelliott requested changes
It would be good to include an example of how to create a team kms key before showing how to reference it. This could go at the top of the team key section, something like:

Example code on how to create a team KMS key, and the permissions needed can be found [here](https://github.com/ministryofjustice/modernisation-platform-environments/blob/b73bba2e9d708efbc0db4492582829f52f00cb60/terraform/environments/sprinkler/kms.tf).

2022-03-28 14:03 UTC, davidkelliott commented on README.md
> +If, however, a customer key is needed then follow the instructions in the section "### How to add your own team kms key".
I can still see this line there? I think it's not needed

2022-03-29 10:14 UTC, davidkelliott approved these changes
👍

2022-03-29 10:14 UTC, merged