NIT-492 Install IAPS NDelius Interface
ministryofjustice/modernisation-platform-ami-builds pull request #235
Opened 2023-02-21 11:37 UTC by silvianahorga-al

2023-02-21 14:44 UTC, ep-93 approved these changes

2023-02-21 15:19 UTC, ep-93 approved these changes

2023-03-02 10:17 UTC, markgov submitted a review, later dismissed
lgtm

2023-03-02 10:41 UTC, ep-93 submitted a review, later dismissed

2023-03-02 11:13 UTC, pete-j-g requested changes

2023-03-02 11:13 UTC, pete-j-g commented on teams/delius-iaps/components/iaps_server/delius_iaps_install_ndelius_interface.yml
> +              if ( Test-Path "C:\Users\Public\Desktop\Migration Utility (Iaps-NDelius IF).lnk") { Remove-Item -Path "C:\Users\Public\Desktop\Migration Utility (Iaps-NDelius IF).lnk" }
This line and line 45 seem to be doing the same action. one of them should be removed

2023-03-02 16:15 UTC, pete-j-g commented on teams/delius-iaps/components/iaps_server/delius_iaps_install_ndelius_interface.yml
> +              if ( Test-Path "C:\Users\Public\Desktop\Migration Utility (Iaps-NDelius IF).lnk") { Remove-Item -Path "C:\Users\Public\Desktop\Migration Utility (Iaps-NDelius IF).lnk" }
redundant line removed

2023-03-06 13:51 UTC, pete-j-g approved these changes

2023-03-06 14:42 UTC, ewastempel approved these changes

2023-03-06 15:35 UTC, merged